[package]
name = "popstack"
version = "0.1.0"
authors = ["Rafał Wrzeszcz <rafal.wrzeszcz@wrzasq.pl>"]

[dependencies]
flate2 = { version = "0.2", features = ["zlib"], default-features = false }
hyper = "0.7"
